export const fakeDatas = {
    itemsReceived: 5,
    curPage: 1,
    nextPage: 2,
    prevPage: null,
    offset: 0,
    itemsTotal: 16,
    pageTotal: 4,
    items: [
      {
        id: 49,
        created_at: 1731260032253,
        title: "tes55",
        price: 123,
        sold: false,
        store_id: 1,
        description: "tetst",
        creator: "",
        photos: [
          {
            access: "public",
            path: "/vault/_xLKZXJA/WVBuKNU2l6Zy0rNEkVTbaCHjTzk/5E1vsA../Screenshot+2024-11-09+at+19.02.36.png",
            name: "Screenshot 2024-11-09 at 19.02.36.png",
            type: "image",
            size: 134727,
            mime: "image/png",
            meta: {
              width: 310,
              height: 244,
            },
            url: "https://x8ki-letl-twmt.n7.xano.io/vault/_xLKZXJA/WVBuKNU2l6Zy0rNEkVTbaCHjTzk/5E1vsA../Screenshot+2024-11-09+at+19.02.36.png",
          },
          {
            access: "public",
            path: "/vault/_xLKZXJA/earc_68ecLIHqI8Fvjxq7FW3qs4/Du0f8w../Screenshot+2024-11-09+at+19.02.33.png",
            name: "Screenshot 2024-11-09 at 19.02.33.png",
            type: "image",
            size: 131766,
            mime: "image/png",
            meta: {
              width: 272,
              height: 254,
            },
            url: "https://x8ki-letl-twmt.n7.xano.io/vault/_xLKZXJA/earc_68ecLIHqI8Fvjxq7FW3qs4/Du0f8w../Screenshot+2024-11-09+at+19.02.33.png",
          },
        ],
      },
      {
        id: 50,
        created_at: 1731261175947,
        title: "test22",
        price: 23,
        sold: false,
        store_id: 1,
        description: "te",
        creator: "test3",
        photos: [
          {
            access: "public",
            path: "/vault/_xLKZXJA/VFzEHLmjciPLCWHKyf8i-iNsXog/XVFqQQ../Screenshot+2024-11-09+at+19.02.33.png",
            name: "Screenshot 2024-11-09 at 19.02.33.png",
            type: "image",
            size: 131766,
            mime: "image/png",
            meta: {
              width: 272,
              height: 254,
            },
            url: "https://x8ki-letl-twmt.n7.xano.io/vault/_xLKZXJA/VFzEHLmjciPLCWHKyf8i-iNsXog/XVFqQQ../Screenshot+2024-11-09+at+19.02.33.png",
          },
        ],
      },
      {
        id: 48,
        created_at: 1731180444556,
        title: "test",
        price: 23,
        sold: false,
        store_id: 1,
        description: "test",
        creator: "",
        photos: [],
      },
      {
        id: 26,
        created_at: 1731169512415,
        title: "cumin langsat",
        price: 16,
        sold: false,
        store_id: 1,
        description:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\u0027s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap int",
        creator: "pierre",
        photos: [
          {
            access: "public",
            path: "/vault/_xLKZXJA/olOSjnZW6l4vovN-JTEEaUYgtIU/J8Do7A../generated-7789.jpg",
            name: "generated-7789.jpg",
            type: "image",
            size: 2135,
            mime: "image/jpeg",
            meta: {
              width: 300,
              height: 300,
            },
            url: "https://x8ki-letl-twmt.n7.xano.io/vault/_xLKZXJA/olOSjnZW6l4vovN-JTEEaUYgtIU/J8Do7A../generated-7789.jpg",
          },
        ],
      },
      {
        id: 23,
        created_at: 1731169512382,
        title: "satsuma sheanut",
        price: 61,
        sold: false,
        store_id: 1,
        description:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\u0027s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap int",
        creator: "pierre",
        photos: [
          {
            access: "public",
            path: "/vault/_xLKZXJA/oOPveBDQ3Z2Hbw5u85O2k9qlySA/rSRPWQ../generated-4587.jpg",
            name: "generated-4587.jpg",
            type: "image",
            size: 2135,
            mime: "image/jpeg",
            meta: {
              width: 300,
              height: 300,
            },
            url: "https://x8ki-letl-twmt.n7.xano.io/vault/_xLKZXJA/oOPveBDQ3Z2Hbw5u85O2k9qlySA/rSRPWQ../generated-4587.jpg",
          },
          {
            access: "public",
            path: "/vault/_xLKZXJA/BSulww10EM8-aP63ijX2L0iWPgA/1CDWEw../Screenshot+2024-11-09+at+17.23.40.png",
            name: "Screenshot 2024-11-09 at 17.23.40.png",
            type: "image",
            size: 81296,
            mime: "image/png",
            meta: {
              width: 250,
              height: 214,
            },
            url: "https://x8ki-letl-twmt.n7.xano.io/vault/_xLKZXJA/BSulww10EM8-aP63ijX2L0iWPgA/1CDWEw../Screenshot+2024-11-09+at+17.23.40.png",
          },
        ],
      },
    ],
  };